name: Set up environment
description: Set up an anaconda-linter environment

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Create Environment
      shell: bash
      if: ${{ steps.cache-conda.outputs.cache-hit == false }}
      # NOTE: We use `sed` to force a Python version in the `environment.yaml` file
      run: |
        conda update -n base -c defaults conda
        source $CONDA/etc/profile.d/conda.sh
        conda init bash
        sed -i 's/- python >=3.*$/- python ${{ inputs.python-version }}.*/' environment.yaml
        if [[ -e  /usr/share/miniconda/envs/anaconda-linter ]]; then rm -rf /usr/share/miniconda/envs/anaconda-linter; fi
        conda env create -f environment.yaml --name anaconda-linter
        conda run --name anaconda-linter pip install .
